spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=d58d19aecc80ff3a96cea8d01156d783b368fcb0fa82d022b706aa7665bff5a2
spring.datasource.password=sk_O6jPvgA3RP1ZKmil7Qa0K
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update